spring:
  application:
    name: inventory-service
  cloud:
    config:
      uri:
      - http://localhost:8888
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/