server:
  port: 8888
spring:
  application:
    name: cloud-config-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pnkjsmwl/practise-config.git
          clone-on-start: true